import React from 'react';
import { Modal } from './ui/Modal';
import { Button } from './ui/Button';
import { AlertTriangle } from 'lucide-react';

interface Props {
  isOpen: boolean;
  onClose: () => void;
}

export const FullDisclaimer: React.FC<Props> = ({ isOpen, onClose }) => {
  return (
    <Modal isOpen={isOpen} onClose={onClose} title="Legal Disclaimer & Terms of Use">
      <div className="p-6 md:p-8 space-y-6 text-slate-600 text-sm leading-relaxed">
        
        <div className="bg-red-50 border border-red-100 rounded-lg p-4 flex gap-3 items-start">
             <AlertTriangle className="w-5 h-5 text-red-600 mt-0.5 shrink-0" />
             <p className="text-red-800 font-bold text-xs tracking-wide">
                 Read carefully before using this application
             </p>
        </div>

        <section className="space-y-2">
            <h4 className="text-slate-900 font-bold text-base">1. Not Medical Advice</h4>
            <p>
                The "AshtonPath" application (the "Service") provides information and calculation tools for educational purposes only. 
                It is <strong>not</strong> a medical device, and the information provided is <strong>not medical advice</strong>. 
                The content is based on the principles of the Ashton Manual but is generated by algorithms that cannot account for your specific biological factors, medical history, or concurrent medications.
            </p>
            <p>
                Always seek the advice of your physician or other qualified health provider with any questions you may have regarding a medical condition or medication taper. 
                Never disregard professional medical advice or delay in seeking it because of something you have read on this application.
            </p>
        </section>

        <section className="space-y-2">
            <h4 className="text-slate-900 font-bold text-base">2. Limitation of Liability</h4>
            <p>
                By using this application, you explicitly agree that the creators, developers, contributors, and hosting providers of AshtonPath shall <strong>not be held liable</strong> for any direct, indirect, incidental, consequential, or exemplary damages, including but not limited to:
            </p>
            <ul className="list-disc pl-5 space-y-1 bg-slate-50 p-3 rounded-md border border-slate-100">
                <li>Personal injury, severe withdrawal symptoms, or death.</li>
                <li>Worsening of medical or psychiatric conditions (e.g., anxiety, depression, seizures).</li>
                <li>Errors, omissions, or inaccuracies in the generated tapering schedules.</li>
                <li>Any loss of data or service interruptions.</li>
            </ul>
        </section>

        <section className="space-y-2">
            <h4 className="text-slate-900 font-bold text-base">3. Assumption of Risk</h4>
            <p>
                Benzodiazepine withdrawal is a serious medical process that can be life-threatening if managed incorrectly. 
                <strong>You assume full responsibility and risk</strong> for your use of this application. 
                You acknowledge that this tool is a visual aid for planning and does not replace the supervision of a prescribing doctor.
            </p>
        </section>

        <section className="space-y-2">
            <h4 className="text-slate-900 font-bold text-base">4. No Doctor-Patient Relationship</h4>
            <p>
                Use of this application does not establish a doctor-patient relationship between you and the developers. 
                No communication within this app should be treated as confidential medical communication protected by HIPAA or similar privacy laws, although we prioritize local data storage for your privacy.
            </p>
        </section>

        <div className="pt-6 border-t border-slate-100 flex justify-end">
            <Button onClick={onClose} variant="secondary">
                Close
            </Button>
        </div>
      </div>
    </Modal>
  );
};